

namespace MockWebApi.Templating
{
    /// <summary>
    /// This is the base class for the tokens generated by the script template parser.
    /// </summary>
    public class Fragment
    {

    }
}