

namespace MockWebApi.Templating
{
    /// <summary>
    /// This is the base class for the tokens generated by the script template parser.
    /// </summary>
    public class ScriptFragment : Fragment
    {

        private string _scriptText;

        public string ScriptText { get; }

        public ScriptFragment(string scriptText)
        {
            _scriptText = scriptText;
        }

    }
}