name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Get Docker Image Version
        shell: pwsh
        run: |
          .\Docker\GetProjectVersion.ps1 | Out-File -append -FilePath $env:GITHUB_ENV

      - name: Check Container Version From Env
        run: |
          echo echo ${{ env.DOCKER_CONTAINER_IMAGE_VERSION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/mockwebapi:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/mockwebapi:${{ env.DOCKER_CONTAINER_IMAGE_VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
