name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish MockWebApi.Client
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: MockWebApi.Client/MockWebApi.Client.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish MockWebApi.Configuration
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: MockWebApi.Configuration/MockWebApi.Configuration.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
